### ISSUE TITLE
STA9750 matata668 MiniProject #00

### ISSUE THREAD

**Issue by matata668** [matata668/STA9750-2024-FALL#1]
Hi @michaelweylandt!

I've created my STA9750 website - check it out!

https://matata668.github.io/STA9750-2024-FALL

**Comment by michaelweylandt** [comment]
Thanks @matata668 !

Peer Feedback:

- @clintavarghese
- @ayrama
- @whaleron

Please a look at the website associated with this GitHub repo
and provide some peer feedback to @matata668.

Website URL should be: https://matata668.github.io/STA9750-2024-FALL/

If that link doesn't work, please check out the GitHub profile for @matata668 and
see if you can help them get it working.

At a minimum, please note:

1. Something you like about the submission.
2. A suggestion on how to improve it.

Feel free to link to other repos, the course documentation, or other useful
examples.

This submission is ungraded, so there's you don't need to provide
a numerical score.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by whaleron** [comment]
@matata668, I really enjoyed your "500 Days of Summer" - it's very artistic and unique! 
If you could provide a link on your website, I'd love to connect.
